services:
  - type: web
    name: real-time-chat-backend
    env: node
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://chatterpillar.netlify.app
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://chatterpillar.netlify.app
      - path: /*
        name: Access-Control-Allow-Methods
        value: GET, POST, PUT, DELETE, OPTIONS
      - path: /*
        name: Access-Control-Allow-Headers
        value: Content-Type, Authorization
      - path: /*
        name: Access-Control-Allow-Credentials
        value: "true"